### ISSUE TITLE
list index out of range when rebasing

### ISSUE THREAD

**Issue by pindab0ter** [ManimCommunity/ManimPango#100]
When using `git-sim merge develop` everything works fine. When trying `git-sim rebase develop` I get this error:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/git-sim", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/git_sim/__main__.py", line 89, in main
    scene.render()
  File "/opt/homebrew/lib/python3.10/site-packages/manim/scene/scene.py", line 223, in render
    self.construct()
  File "/opt/homebrew/lib/python3.10/site-packages/git_sim/git_sim.py", line 56, in construct
    self.command.execute()
  File "/opt/homebrew/lib/python3.10/site-packages/git_sim/git_sim_rebase.py", line 48, in execute
    current = self.commits[i]
IndexError: list index out of range
```

I tried this on Apple Silicon, on a fresh installation as of 2023-01-23.

**Comment by naveen521kk** [comment]
Can you elaborate on what `git-sim` is? I think you should probably contact the support for git-sim rather than making an issue here so they can help you https://github.com/initialcommit-com/git-sim.

I'm closing this issue because it's not related to ManimPango.

**Comment by pindab0ter** [comment]
Apologies for posting it in the wrong repo.
