### ISSUE TITLE
setup.py get_version fails on Python 3.13

### ISSUE THREAD

**Issue by stefanor** [ManimCommunity/ManimPango#112]
```
$ python3.13
Python 3.13.0rc2 (main, Sep  7 2024, 08:52:38) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def get_version():
...     version_file = "manimpango/_version.py"
...     with open(version_file) as f:
...         exec(compile(f.read(), version_file, "exec"))
...     return locals()["__version__"]
... 
>>> get_version()
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    get_version()
    ~~~~~~~~~~~^^
  File "<python-input-0>", line 5, in get_version
    return locals()["__version__"]
           ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: '__version__'
>>> 
```

Could be due to: https://docs.python.org/3.13/whatsnew/3.13.html#defined-mutation-semantics-for-locals

**Comment by naveen521kk** [comment]
Thanks for reporting! I've already fixed this issue it in https://github.com/ManimCommunity/ManimPango/pull/111. That PR requires some more work, so I'll close this issue when merging it and release a new version.
