### ISSUE TITLE
manim installation issue

### ISSUE THREAD

**Issue by ramc77** [ManimCommunity/ManimPango#39]
Dear developers!
I have tried to install manim many times as per instructions of tutorial but failed to run the manim. I have MacBook Pro 16inch running Big Sur latest version. Here is error message what I get (latex is installed properly): 

ramchand@MacBook-Pro manim-3b % python3 -m manim example_scenes.py WriteStuff -pl

Traceback (most recent call last):
  File "/Users/ramchand/manim-3b/manimlib/extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/ramchand/manim-3b/manimlib/scene/scene.py", line 54, in __init__
    self.construct()
  File "example_scenes.py", line 98, in construct
    example_text = TextMobject(
  File "/Users/ramchand/manim-3b/manimlib/mobject/svg/tex_mobject.py", line 143, in __init__
    SingleStringTexMobject.__init__(
  File "/Users/ramchand/manim-3b/manimlib/mobject/svg/tex_mobject.py", line 43, in __init__
    file_name = tex_to_svg_file(
  File "/Users/ramchand/manim-3b/manimlib/utils/tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/Users/ramchand/manim-3b/manimlib/utils/tex_file_writing.py", line 64, in tex_to_dvi
    raise Exception(
Exception: Latex error converting to dvi. See log output above or the log file: /Users/ramchand/manim-3b/manimlib/files/Tex/47f78a457bde38f5.log

Please help me
Thank you very much!

**Comment by naveen521kk** [comment]
Wrong Repository. Please make one in https://github.com/3b1b/manim
