### ISSUE TITLE
Failed to install via pip in GitHub Action

### ISSUE THREAD

**Issue by TonyCrane** [ManimCommunity/ManimPango#53]
Sorry to bother you, I'm currently preparing for an important exam and I don't have much time to spend on GitHub. But I found that the Action used to build the document in [3b1b/manim](https://github.com/3b1b/manim) failed in a run 3 days ago (https://github.com/3b1b/manim/runs/2300857732). The following is the error message:
```text
Collecting manimpango<0.3.0',>=0.2.0
  Downloading ManimPango-0.2.5.post0.tar.gz (455 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmphiy_wfhh get_requires_for_build_wheel /tmp/tmph92gvin_
       cwd: /tmp/pip-install-t40xq14y/manimpango
  Complete output (33 lines):
  Package pangocairo was not found in the pkg-config search path.
  Perhaps you should add the directory containing `pangocairo.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'pangocairo' found
  Traceback (most recent call last):
    File "setup.py", line 129, in check_min_version
      check_call(command, stdout=subprocess.DEVNULL)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/tmphiy_wfhh", line 280, in <module>
      main()
    File "/tmp/tmphiy_wfhh", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmphiy_wfhh", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-18yciq1c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-18yciq1c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-18yciq1c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-18yciq1c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 194, in <module>
      _pkg_config.check_min_version(MINIMUM_PANGO_VERSION)
    File "setup.py", line 132, in check_min_version
      raise RequiredDependencyException(f"{self.name} >= {version} is required")
  __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmphiy_wfhh get_requires_for_build_wheel /tmp/tmph92gvin_ Check the logs for full command output.
Error: Process completed with exit code 1.
```
This run corresponds to https://github.com/3b1b/manim/commit/f6291d7e82b49b419086a70afc075694931669e7, which merged https://github.com/3b1b/manim/pull/1421. But the check for this pull request passed a month ago: https://github.com/3b1b/manim/actions/runs/609607503.
So I think it is a problem with the installation of the new version of ManimPango.

This may be an easy problem to deal with. But please forgive me for not having time to fix it at the moment. So can you take a look at this problem and create a PR in 3b1b/manim to fix it?

**Comment by naveen521kk** [comment]
Sure, it is as simple as installing Pango through apt.

**Comment by TonyCrane** [comment]
It succeeded. Thank you!

**Comment by bth5032** [comment]
> Sure, it is as simple as installing Pango through apt.

`sudo apt-get install libsdl-pango-dev `

**Comment by Myzel394** [comment]
@bth5032 Do you know the equivalent for `dnf`?

**Comment by 727yubin** [comment]
> @bth5032 Do you know the equivalent for `dnf`?

`dnf install pango-devel`

**Comment by naveen521kk** [comment]
> > Sure, it is as simple as installing Pango through apt.
> 
> `sudo apt-get install libsdl-pango-dev `

Actually, it should be `sudo apt-get install libpango1.0-dev` and not the other one, but it should've worked, I guess.

**Comment by ashish111333** [comment]
> > @bth5032 Do you know the equivalent for `dnf`?
> 
> `dnf install pango-devel`

hey this helped a lot,thanks.

**Comment by hfikry92** [comment]
for mac os
`brew install pango`

**Comment by brownsloth** [comment]
> > Sure, it is as simple as installing Pango through apt.
> 
> `sudo apt-get install libsdl-pango-dev `

Works for Ubuntu 22.04 on my Dell Latitude.
Thanks.
