### ISSUE TITLE
M1 Mac Installation Problem

### ISSUE THREAD

**Issue by MichealLea** [ManimCommunity/ManimPango#75]
Initially, I followed the instructions of the Anaconda Installations command lines in [Installation of manim](https://github.com/3b1b/manim).
My computer is Macbook Air (M1 chip, 8 cores GPU, 16 Gb Memory).

Here, is the problem described as an import error when I tried to run a brief code 
`manimgl example_scenes.py OpeningManimExample`

OUTPUT:
```
Traceback (most recent call last):
  File "/Users/micheallea/miniforge3/envs/manim/lib/python3.8/site-packages/manimpango/__init__.py", line 14, in <module>
    from .cmanimpango import *  # noqa: F403,F401
ImportError: dlopen(/Users/micheallea/miniforge3/envs/manim/lib/python3.8/site-packages/manimpango/cmanimpango.cpython-38-darwin.so, 2): Library not loaded: @rpath/libpangocairo-1.0.0.dylib
  Referenced from: /Users/micheallea/miniforge3/envs/manim/lib/python3.8/site-packages/manimpango/cmanimpango.cpython-38-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/micheallea/miniforge3/envs/manim/bin/manimgl", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "/Users/micheallea/miniforge3/envs/manim/bin/manimgl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/micheallea/miniforge3/envs/manim/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/micheallea/miniforge3/envs/manim/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/micheallea/manim/manimlib/__init__.py", line 14, in <module>
    from manimlib.animation.numbers import *
  File "/Users/micheallea/manim/manimlib/animation/numbers.py", line 2, in <module>
    from manimlib.mobject.numbers import DecimalNumber
  File "/Users/micheallea/manim/manimlib/mobject/numbers.py", line 3, in <module>
    from manimlib.mobject.svg.text_mobject import Text
  File "/Users/micheallea/manim/manimlib/mobject/svg/text_mobject.py", line 15, in <module>
    import manimpango
  File "/Users/micheallea/miniforge3/envs/manim/lib/python3.8/site-packages/manimpango/__init__.py", line 35, in <module>
    raise ImportError(msg)
ImportError: 

ManimPango could not import and load the necessary shared libraries.
This error may occur when ManimPango and its dependencies are improperly set up.
Please make sure the following versions are what you expect:

    * ManimPango v0.3.1, Python v3.8.11

If you believe there is a greater problem,
feel free to contact us or create an issue on GitHub:

    * Discord: https://discord.gg/mMRrZQW
    * GitHub: https://github.com/ManimCommunity/ManimPango/issues

Original error: dlopen(/Users/micheallea/miniforge3/envs/manim/lib/python3.8/site-packages/manimpango/cmanimpango.cpython-38-darwin.so, 2): Library not loaded: @rpath/libpangocairo-1.0.0.dylib
  Referenced from: /Users/micheallea/miniforge3/envs/manim/lib/python3.8/site-packages/manimpango/cmanimpango.cpython-38-darwin.so
  Reason: image not found
```

**Comment by naveen521kk** [comment]
If you are using conda, install pango from conda-forge(`conda install pango`), first and then install ManimPango, use `pip install manimpango --force --no-cache` to reinstall.

**Comment by naveen521kk** [comment]
Closing due to inactivity.
